
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
  valkey:
    restart: always
    image: valkey/valkey:latest
    volumes:
      - valkey_data:/usr/local/etc/valkey
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - 8000:8000
  worker:
    command: ["/bin/sh", "-c", "rq worker --with-scheduler --url redis://valkey:6379"]
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
volumes:
  mongo_data:
  valkey_data:
